In [1]:
from azureml import Workspace

ws = Workspace(
    workspace_id='7eba2ffdc55c4bf8afc0c8bf59a6bae4',
    authorization_token='114ab543068a447ead6e42797939b154',
    endpoint='https://studioapi.azureml.net')
ds = ws.datasets['Churn.csv']
frame = ds.to_dataframe()

In [2]:
frame

,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,REPORTED_3ISFACTION,REPORTED_USAGE_LEVEL,3_CHANGE_OF_PLAN,CHURN
0,0,45094,0,0,668409,182,1,9,4,1,3,1
1,0,156268,0,9,223030,703,1,4,3,1,3,1
2,0,29679,53,58,289246,222,5,1,0,4,3,0
3,0,34200,108,66,180900,233,12,1,0,1,3,0
4,1,102370,0,17,259047,525,1,6,4,0,3,1
5,1,88490,0,6,984146,283,1,4,0,0,4,1
6,0,45370,182,19,187214,863,12,5,0,1,0,0
7,1,115339,0,23,730166,429,1,6,2,1,4,1
8,1,48886,0,23,183889,239,0,4,3,2,4,1
9,1,83827,0,7,579943,255,4,5,1,3,3,1
10,0,75859,0,5,266790,368,5,6,0,1,0,1
11,0,119745,41,44,269792,499,3,2,0,1,4,1
12,1,98258,190,22,297399,303,22,5,0,4,4,1
13,0,36819,223,0,366634,147,13,11,4,0,3,0
14,0,45758,67,61,293683,213,4,6,1,0,3,0
15,0,65343,0,55,871972,785,4,1,4,1,1,1
16,0,151267,221,14,897373,726,26,5,0,1,4,0
17,1,124336,0,0,459136,587,5,15,0,4,2,1
18,0,119512,51,31,248566,229,5,2,4,4,3,0
19,1,75947,0,0,721881,393,1,14,1,0,3,1
20,1,137729,46,11,207827,594,5,4,1,1,4,1
21,1,69169,235,0,686451,384,17,8,4,3,0,1
22,0,157812,188,0,920460,515,14,15,0,1,3,1
23,1,34181,0,60,996116,136,1,2,0,0,3,0
24,0,70000,0,83,620731,321,1,1,0,0,3,1
25,1,84215,40,20,651590,301,5,5,0,1,4,1
26,1,52650,0,23,673502,269,5,5,2,1,3,1
27,1,32450,86,52,587726,535,1,2,0,2,0,1
28,0,31086,0,0,442509,228,3,15,2,4,3,0
29,1,66329,166,0,549879,340,27,14,1,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
13970,0,65452,172,0,761792,284,12,13,0,1,4,0
13971,0,105034,0,0,694417,492,1,12,4,1,2,1
13972,0,69409,0,0,620081,269,1,10,0,1,0,1
13973,0,83080,0,29,243908,372,0,2,2,4,3,0
13974,0,28843,175,6,244238,234,11,4,0,3,3,0
13975,1,22165,0,0,212375,168,25,5,0,4,4,1
13976,0,139048,0,0,206140,407,1,5,4,1,4,0
13977,1,147481,0,52,160464,897,0,2,0,1,0,0
13978,1,78676,242,48,433144,287,25,2,0,2,1,0
13979,0,68689,0,6,296001,813,0,4,0,4,0,1
13980,1,36209,184,43,208785,186,25,2,0,4,4,0
13981,0,109033,211,0,712273,548,12,13,1,1,4,0
13982,0,148802,0,56,797083,632,1,1,2,4,0,0
13983,1,64528,0,9,920241,314,1,5,0,1,3,1
13984,1,32914,0,14,584523,295,16,4,0,1,4,1
13985,0,131284,90,0,585436,524,5,13,4,1,0,0
13986,0,138222,73,12,233601,869,1,6,0,4,0,1
13987,1,112698,62,0,516918,460,4,14,0,1,0,0
13988,0,40683,212,15,844664,188,24,5,0,0,0,1
13989,1,116071,0,0,442070,340,1,13,0,4,0,0
13990,0,147084,0,76,154076,261,5,2,1,1,0,0
13991,0,95956,183,18,750582,347,29,6,4,4,3,0
13992,0,80576,209,22,789085,341,27,5,0,4,4,0
13993,1,33181,45,50,876026,226,3,2,1,4,3,1
13994,1,152256,0,16,442567,242,1,6,0,4,3,1
13995,1,81787,50,0,880490,698,5,1,4,0,0,1
13996,1,102331,216,16,260156,452,11,6,4,3,3,0
13997,0,129228,0,48,293351,284,5,2,4,0,3,0
13998,1,47398,0,15,434358,301,0,6,0,3,3,1
13999,1,73795,159,0,759481,366,16,11,0,2,3,1

In [5]:
import pandas as pd
y = targets = labels = frame["CHURN"].values

columns = ["COLLEGE", "INCOME", "OVER_15MINS_CALLS_PER_MONTH", "HOUSE", "REPORTED_3ISFACTION"]
features = frame[list(columns)].values
features

array([[     0,  45094,      1, 668409,      4],
       [     0, 156268,      1, 223030,      3],
       [     0,  29679,      5, 289246,      0],
       ...,
       [     0, 129228,      5, 293351,      4],
       [     1,  47398,      0, 434358,      0],
       [     1,  73795,     16, 759481,      0]])

In [6]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(X, y)

NameError: name 'X' is not defined

In [7]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
X = imp.fit_transform(features)
X

array([[  0.00000000e+00,   4.50940000e+04,   1.00000000e+00,
          6.68409000e+05,   4.00000000e+00],
       [  0.00000000e+00,   1.56268000e+05,   1.00000000e+00,
          2.23030000e+05,   3.00000000e+00],
       [  0.00000000e+00,   2.96790000e+04,   5.00000000e+00,
          2.89246000e+05,   0.00000000e+00],
       ...,
       [  0.00000000e+00,   1.29228000e+05,   5.00000000e+00,
          2.93351000e+05,   4.00000000e+00],
       [  1.00000000e+00,   4.73980000e+04,   0.00000000e+00,
          4.34358000e+05,   0.00000000e+00],
       [  1.00000000e+00,   7.37950000e+04,   1.60000000e+01,
          7.59481000e+05,   0.00000000e+00]])

In [8]:
features

array([[     0,  45094,      1, 668409,      4],
       [     0, 156268,      1, 223030,      3],
       [     0,  29679,      5, 289246,      0],
       ...,
       [     0, 129228,      5, 293351,      4],
       [     1,  47398,      0, 434358,      0],
       [     1,  73795,     16, 759481,      0]])

In [9]:
X= features

In [10]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(X, y)

In [23]:
from sklearn.externals.six import StringIO
with open("Churn.dot", 'w') as f:
    f = tree.export_graphviz(clf, out_file=f, feature_names=columns)

In [19]:
dot -Tpng churn.dot -o churn.png

SyntaxError: invalid syntax (<ipython-input-19-87ce5789710c>, line 1)

In [24]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
clf = tree.DecisionTreeClassifier()
clf = clf.fit(iris.data, iris.target)

FileNotFoundError: [Errno 2] No such file or directory: 'dot'